### ISSUE TITLE
Current module alias doesn't work in export list

### ISSUE THREAD

**Issue by LiisiKerik** [tfausak/imp#34]
First of all, thank you for this package! Being able to alias the current module is very helpful, especially when the full module name consists of more than one part.

I've noticed that aliasing the current module doesn't work in export list.

I've reduced it to a minimal working example. If I have a cabal file like this one:

```
cabal-version: 3.8
name: Kawaii-Parser
version: 0.0.0
library
  build-depends: base, imp
  exposed-modules: Parser.Errors, Parser.Parser
  ghc-options: -Wall -fplugin=Imp -fplugin-opt=Imp:--alias=_:This
```

And those two modules:

```
module Parser.Errors (Error (..)) where
  data Error = Ambiguity | Attempt_to_recover_a_filter_error | Incomplete_tokenisation
```

and

```
module Parser.Parser (This.Error (..), test) where
  import Parser.Errors as Errors
  data Error error = Filter_error error | Parse_error
  test :: This.Error ()
  test = Parse_error
```

then I get an error:

_Not in scope: type constructor or class \`This.Error'
NB: no module named \`This' is imported._

Another thing I've noticed is that it seems to slow down the build by a lot for a small project. I'm not sure if it's about the way I use the plugin or not. Maybe I'm doing something wrong there.

**Comment by tfausak** [comment]
Thanks for reporting this bug!

This happens because Imp doesn't look at export lists at all. It only looks at declarations. Specifically the [`hsmodDecls`](https://downloads.haskell.org/~ghc/9.12.1/docs/libraries/ghc-9.12.1-4681/GHC-Hs.html#v:hsmodDecls) field.

https://github.com/tfausak/imp/blob/156f80a2d4ace62716c24d714a46bc67287fe174/source/library/Imp.hs#L92

I think it would be reasonable to extend this to also look at `hsmodExports`. 

With regards to performance, nothing immediately comes to mind. Perhaps #22 could be turned into a proper benchmark. Please open another issue if you'd like.
